"name": "Release"
"on":
  push:
    tags:
      - "mc-*"

jobs:
  release:
    runs-on: docker
    steps:
      - uses: actions/checkout@v4
      - name: Install git-cliff
        run: |
          curl -LO https://github.com/orhun/git-cliff/releases/download/v2.14.2/git-cliff-2.14.2-x86_64-unknown-linux-gnu.tar.gz
          tar -xzf git-cliff-2.14.2-x86_64-unknown-linux-gnu.tar.gz
          chmod +x git-cliff-*/git-cliff
          mv git-cliff-*/git-cliff /usr/local/bin
          rm git-cliff-*.tar.gz
          rm -rf git-cliff-*
      - name: Generate changelog
        run: |
          git-cliff -o CHANGELOG.md
      - name: Debug changelog
        run: |
          cat CHANGELOG.md